export default {
    content: [
        './resources/views/**/*.blade.php',
        './app/View/Components/**/*.php',
        './app/Http/Controllers/**/*.php',
    ],
    theme: {
        extend: {
            colors: {
                orbital: {
                    void: '#0A0A0B',
                    surface: '#141416',
                    card: '#1C1C1F',
                    elevated: '#242429',
                    border: 'rgba(255, 255, 255, 0.06)',
                    'border-hover': 'rgba(255, 255, 255, 0.10)',
                    indigo: '#6366F1',
                    cyan: '#22D3EE',
                    rose: '#FB7185',
                    amber: '#FBBF24',
                    text: '#F5F5F7',
                    muted: '#8E8E93',
                    dim: '#48484F',
                },
                ink: '#0A0A0B',
                muted: '#8E8E93',
                paper: '#141416',
                surface: '#1C1C1F',
                brand: {
                    DEFAULT: '#6366F1',
                    dark: '#4F46E5',
                    light: '#818CF8',
                    soft: 'rgba(99, 102, 241, 0.12)',
                    glow: 'rgba(99, 102, 241, 0.25)',
                },
                navy: {
                    DEFAULT: '#0A0A0B',
                    2: '#141416',
                    3: '#1C1C1F',
                },
                accent: {
                    teal: '#22D3EE',
                    amber: '#FBBF24',
                    green: '#10B981',
                    red: '#FB7185',
                    blue: '#6366F1',
                },
            },
            boxShadow: {
                'xs':   '0 1px 2px rgba(0, 0, 0, 0.30)',
                'sm':   '0 4px 12px rgba(0, 0, 0, 0.40)',
                'soft': '0 8px 24px rgba(0, 0, 0, 0.45)',
                'md':   '0 12px 40px rgba(0, 0, 0, 0.50)',
                'lg':   '0 24px 64px rgba(0, 0, 0, 0.60)',
                'glow': '0 0 20px rgba(99, 102, 241, 0.20)',
                'glow-cyan': '0 0 20px rgba(34, 211, 238, 0.20)',
                'glow-rose': '0 0 20px rgba(251, 113, 133, 0.20)',
            },
            borderRadius: {
                'sm':    '6px',
                'md':    '10px',
                'lg':    '16px',
                'xl':    '24px',
                'pill':  '9999px',
            },
            fontFamily: {
                sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
                mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
            },
            fontSize: {
                'micro': ['11px', { lineHeight: '1.4', letterSpacing: '0.02em' }],
                'caption': ['12px', { lineHeight: '1.5', letterSpacing: '0.01em' }],
                'body': ['14px', { lineHeight: '1.6', letterSpacing: '0' }],
                'h3': ['18px', { lineHeight: '1.4', letterSpacing: '0' }],
                'h2': ['24px', { lineHeight: '1.3', letterSpacing: '0' }],
                'h1': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
                'display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
            },
            spacing: {
                '18': '72px',
                '22': '88px',
                '26': '104px',
                '30': '120px',
            },
            transitionDuration: {
                '150': '150ms',
                '200': '200ms',
                '250': '250ms',
            },
        },
    },
    corePlugins: {
        preflight: false,
    },
    plugins: [],
};

