<?php

return [
    'custom_source_path' => env('ZODPANEL_CUSTOM_SOURCE_PATH', base_path('../zodpanel-hestia-custom-backup/usr/local/hestia')),
    'custom_backup_path' => env('ZODPANEL_CUSTOM_BACKUP_PATH', base_path('../zodpanel-hestia-custom-backup')),
    'hestia_install_url' => env('ZODPANEL_HESTIA_INSTALL_URL', 'https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh'),
    'backup_repo' => env('ZODPANEL_BACKUP_REPO', 'https://github.com/zeewebprosandbox/zodpanel-hestia-custom-backup'),
    'whmlab_repo' => env('WHMLAB_BACKUP_REPO', 'https://github.com/zeewebprosandbox/whmlab2-backup'),
    'github_token' => env('ZODPANEL_GITHUB_TOKEN', env('GITHUB_TOKEN')),
    'live' => [
        'host' => env('ZODPANEL_LIVE_HOST', 'zodpanel.zodhost.com'),
        'ssh_port' => env('ZODPANEL_LIVE_SSH_PORT', 22),
        'ssh_username' => env('ZODPANEL_LIVE_SSH_USER', 'root'),
        'ssh_password' => env('ZODPANEL_LIVE_SSH_PASSWORD'),
    ],
    'custom_file_paths' => [
        '/usr/local/hestia/bin/zodpanel-ssl-sync',
        '/usr/local/hestia/bin/v-configure-zodpanel-ssl-automation',
        '/usr/local/hestia/bin/v-zodpanel-save-package-features',
        '/usr/local/hestia/bin/v-zodpanel-run-domain-command',
        '/usr/local/hestia/bin/v-add-user-pma-temp-user',
        '/usr/local/hestia/web/css/zodpanel-modules.css',
        '/usr/local/hestia/web/inc/zodpanel_modules.php',
        '/usr/local/hestia/web/api/whmlab/index.php',
        '/usr/local/hestia/web/list/modules/index.php',
        '/usr/local/hestia/web/templates/includes/css.php',
        '/usr/local/hestia/web/templates/includes/panel.php',
        '/usr/local/hestia/web/templates/pages/list_modules.php',
        '/usr/local/hestia/web/templates/pages/list_web.php',
        '/usr/local/hestia/web/templates/pages/list_db.php',
        '/usr/local/hestia/web/index.php',
        '/usr/local/hestia/web/fm/configuration.php',
        '/usr/local/hestia/web/fm/dist/css/hst-custom.css',
        '/usr/local/hestia/web/fm/dist/js/app.js',
        '/usr/local/hestia/web/fm/domains/index.php',
        '/usr/local/hestia/web/open/phpmyadmin/index.php',
        '/usr/local/hestia/nginx/conf/nginx.conf',
        '/usr/share/phpmyadmin/hestia-sso.php',
        '/etc/phpmyadmin/conf.d/00-hestia-sso.php',
    ],
];
